package ch.hearc.dfts;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;

//Default test class generated by Eclipse

@SpringBootTest
class DftsApplicationTests {

	@Test
	void contextLoads() {
	}

}
